feat: Выгрузка Хранилища значений в файлы
Pr-Mex/vanessa-automation pull request #1488
Opened 2022-01-03 11:14 UTC by KrapivinAndrey

Сделанные изменения

- Доработка механизма Подготовка и загрузка данных
- В тестовые конфигурации добавлен реквизит с типом ХранилищеЗначения в спр. Товары
- Тест на новый функционал

2022-01-03 11:15 UTC, KrapivinAndrey commented
run tests

2022-01-03 11:15 UTC, KrapivinAndrey commented
@DitriXNew

2022-01-03 13:48 UTC, DitriXNew requested changes

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml
> +					<v8:lang>ru</v8:lang>
en

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml
> +							<v8:lang>ru</v8:lang>
en

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml
> +					<v8:content>Path
перенос лишний

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			If Not (Left(TypeName, 10) = "CatalogRef" Or Left(TypeName, 11) = "DocumentRef" Or Left(TypeName, 29) = "ChartOfCharacteristicTypesRef")
Магические числа, надо преобразовать в переменные. И почему именно так сделано?

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +Function GeValuetStringRepresentation(DataValue, RefReplaceMetadataObjects, ParamsValueStorage)
мне кажется что в целом лучше этот параметр ParamsValueStorage сделать глобальным и не пропихивать его везде, а если уже пропихивать, то тогда надо сделать рефакт и вынести все параметры в структуры.

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +						+ ?(Right(ParamsValueStorage.PathToUpload, 1) = "/", "", "/")
а если будет обратный слешь?

2022-01-03 13:48 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			While StrLen(Ch) < min(LengthArray[Kkk], 1024) Do
магическое число

2022-01-03 15:20 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			If Not (Left(TypeName, 10) = "CatalogRef" Or Left(TypeName, 11) = "DocumentRef" Or Left(TypeName, 29) = "ChartOfCharacteristicTypesRef")
СтрНачинаетсяС не поддерживается до 8.3.8 - а такой режим запуска у базы для тестирования VA

2022-01-03 16:37 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml
> +					<v8:lang>ru</v8:lang>
fix

2022-01-03 16:37 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml
> +							<v8:lang>ru</v8:lang>
fix

2022-01-03 16:37 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml
> +					<v8:content>Path
fix

2022-01-03 16:37 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			If Not (Left(TypeName, 10) = "CatalogRef" Or Left(TypeName, 11) = "DocumentRef" Or Left(TypeName, 29) = "ChartOfCharacteristicTypesRef")
fix

2022-01-03 16:38 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +Function GeValuetStringRepresentation(DataValue, RefReplaceMetadataObjects, ParamsValueStorage)
fix

2022-01-03 16:39 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			While StrLen(Ch) < min(LengthArray[Kkk], 1024) Do
Это уже было

2022-01-03 16:47 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +						+ ?(Right(ParamsValueStorage.PathToUpload, 1) = "/", "", "/")
не будет. При инициализации структуры слеши приводятся к единому типу

2022-01-03 17:08 UTC, KrapivinAndrey commented
run tests

2022-01-03 17:28 UTC, KrapivinAndrey commented
run tests

2022-01-03 17:50 UTC, KrapivinAndrey commented
run tests

2022-01-04 14:21 UTC, DitriXNew approved these changes

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +Procedure PathToUploadНачалоВыбора(Item, Choose, StandardProcessing)
если уж на инглише, то пусть будет все на инглишще :)

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			If Not (Documents.AllRefsType().ContainsType(TypeVal)
Вынеси лучше условие в отдельную переменную и дай внятное название, а то я что то не могу понять что это за код. Уже не помню :)

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +Function ParseStringValue(Val ParsingValue, Val ValueType, workspaceRoot)
workspaceRoot тоже везде пробрасывается, может его проще вынести тоже в экспортные? Зачем его везде передавать и про него помнить. Так получится сделать?

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +	If Left(ParsingValue, 17) = "ValueStoragePath:" Then
Магическое число. Надо в переменную внятную вынести

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
>  	If Left(ParsingValue, 16) = "FindByAttribute:" Then
магические числа

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +						+ ?(Right(ParamsValueStorage.PathToUpload, 1) = "/", "", "/")
ну тогда может там сразу и сделать приведение к одному виду? Зачем это тянуть ниже. Оно же не один раз встречается

2022-01-04 14:21 UTC, DitriXNew commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +			While StrLen(Ch) < min(LengthArray[Kkk], 1024) Do
ну так так код и рефакторится, кто то задел, кто то заметил, вот и качество растет :)  Но судя по коду, числа раньше там не было, а это новый код.

2022-01-04 14:22 UTC, DitriXNew commented
В целом - круто, если не видишь смысла исправлять мои замечания - просто пометь их как закрытые и все.

2022-01-04 20:43 UTC, Pr-Mex commented
Да, согласен.

2022-01-04 20:47 UTC, nixel2007 commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +	If Left(ParsingValue, 17) = "ValueStoragePath:" Then
ну тут очевидно же. от увеличения переменной когнитивная нагрузка только вырастет. как ее назвать? КоличествоБуквВСтрокеValueStoragePathДвоеточие?

2022-01-05 09:40 UTC, KrapivinAndrey commented on VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
> +	If Left(ParsingValue, 17) = "ValueStoragePath:" Then
Я думаю это следствие того, что нет поддержки СтрНачинаетсяС, так сказать альтернативный вариант. Я бы использовал СтрНайти - но для единообразия всего кода - такой вариант

2022-01-05 11:46 UTC, KrapivinAndrey commented
Поправил замечания. И тесты

2022-01-05 11:46 UTC, KrapivinAndrey commented
run tests

2022-01-06 05:40 UTC, Pr-Mex commented
@KrapivinAndrey 
http://84.237.195.35:32005/job/VAPullRequestCheck/526/allure/#behaviors/d1e6ba623b21ac33774d94a165d5e1fd/fc5014ca0cc2cf9d/
Там в колонке Изображение пути разные.

2022-01-06 12:54 UTC, KrapivinAndrey commented
@Pr-Mex Вечная проблема с / в КаталогПроекта и workspaceRoot

2022-01-06 13:50 UTC, Pr-Mex commented
Run tests

2022-01-06 14:39 UTC, KrapivinAndrey commented
@Pr-Mex надо перезапустить тесты

2022-01-07 08:55 UTC, KrapivinAndrey commented
Run tests

2022-01-08 04:48 UTC, Pr-Mex commented
@KrapivinAndrey 
Тесты прошли!
Я тогда в понедельник ещё раз реквест весь целиком гляну и приму. А то сейчас с телефона.

2022-01-10 16:21 UTC, Pr-Mex commented
Спасибо!

2022-01-10 16:21 UTC, merged